FROM golang:1.24

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/air-verse/air@latest

RUN apt-get update && apt-get install -y netcat-openbsd

RUN chmod +x wait-for-it.sh

RUN go mod tidy

EXPOSE 8082

CMD ["air"]