services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - cockroachdb
      - init-db
    env_file:
      - .env
    command: >
      sh -c "
      until nc -z ${DB_HOST} ${DB_PORT}; do
        echo 'Esperando a CockroachDB...';
        sleep 2;
      done;
      ./main"

  cockroachdb:
    image: cockroachdb/cockroach:v23.1.11
    container_name: cockroachdb
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD", "cockroach", "sql", "--insecure", "--execute=SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  init-db:
    image: cockroachdb/cockroach:v23.1.11
    depends_on:
      cockroachdb:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        cockroach sql --insecure --host=cockroachdb -e 'CREATE DATABASE IF NOT EXISTS bdg';
      "

volumes:
  cockroach-data:
